/*jshint esversion: 8 */
/*global */

export const pages = [{
    id: 'divider1',
    type: 'divider',
    size: 'wide',
    dropdownMenu: 'mobile',
    footerItem: false,
  },
  {
    id: 'who-was-thoreau',
    type: 'popup',
    enabled: true,
    dropdownMenu: 'mobile',
    name: 'Who was Thoreau?',
    location: "index.html",
    footerItem: true,
  },
  {
    id: 'divider2',
    type: 'divider',
    dropdownMenu: 'mobile',
    footerItem: false,
  },
  {
    id: 'snowshoes',
    type: 'artifact',
    enabled: true,
    index: 0,
    dropdownMenu: 'all',
    name: 'Thoreau’s Snowshoes',
    location: "snowshoes.html",
    src: "media/images/snowshoes/thoreau-snowshoes-close.png",
    width: 456,
    height: 557,
    footerItem: false,
  },
  {
    id: 'spyglass',
    type: 'artifact',
    enabled: true,
    index: 1,
    dropdownMenu: 'all',
    name: 'Thoreau’s Spyglass',
    location: "spyglass.html",
    src: "media/images/spyglass/spyglass.png",
    width: 697,
    height: 236,
    footerItem: false,
  },
  {
    id: 'lock-and-key',
    type: 'artifact',
    enabled: true,
    index: 2,
    dropdownMenu: 'all',
    name: 'Lock and Key (Concord Jail)',
    location: "lock-and-key.html",
    src: "media/images/lock-and-key/lock-and-key.png",
    width: 409,
    height: 549,
    footerItem: false,
  },
  {
    id: 'walking-stick',
    type: 'artifact',
    enabled: true,
    index: 3,
    dropdownMenu: 'all',
    name: 'Thoreau’s Walking Stick',
    location: "walking-stick.html",
    src: "media/images/walking-stick/walking-stick.png",
    width: 641,
    height: 567,
    footerItem: false,
  },
  {
    id: 'flute',
    type: 'artifact',
    enabled: true,
    index: 4,
    dropdownMenu: 'all',
    name: 'Thoreau’s Flute',
    location: "flute.html",
    src: "media/images/flute/flute.png",
    width: 808,
    height: 200,
    footerItem: false,
  },
  {
    id: 'desk',
    type: 'artifact',
    enabled: true,
    index: 5,
    dropdownMenu: 'all',
    name: 'Thoreau’s Desk',
    location: "desk.html",
    src: "media/images/desk/desk.png",
    width: 508,
    height: 619,
    footerItem: false,
  },
  {
    id: 'main-menu',
    type: 'link',
    enabled: true,
    fragment: true,
    name: 'Main Menu',
    dropdownMenu: 'all',
    location: "index.html",
    footerItem: false,
  },
  {
    id: 'divider3',
    type: 'divider',
    dropdownMenu: 'mobile',
    footerItem: false,
  },
  {
    id: 'thoreau-collection',
    type: 'link',
    enabled: true,
    name: 'Thoreau Collection',
    dropdownMenu: 'mobile',
    location: "http://www.concordcollection.org/mExhibit.aspx?rID=Thoreau%20Collection&dir=PERMANENT",
    footerItem: true,
  },
  {
    id: 'educator-resources',
    type: 'link',
    enabled: true,
    name: 'Educator Resources',
    dropdownMenu: 'mobile',
    location: "https://concordmuseum.org/education/neh-landmarks-workshop/workshop-resources-from-2019/",
    footerItem: true,
  }
]
